// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace GTR_AUTOMATED.Features.Train_Presentation.YardnMaster
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("GTR-UAT-RTS-027 Move Request Tab - View Move Requests")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class GTR_UAT_RTS_027MoveRequestTab_ViewMoveRequestsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Train_Presentation/Yardn Master", "GTR-UAT-RTS-027 Move Request Tab - View Move Requests", "As a Panel Operations Manager, I want to view active Move Requests on units in th" +
                "e Yard", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "GTR-UAT-RTS-027.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Train_Presentation/Yardn Master/GTR-UAT-RTS-027.feature.ndjson", 6);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("01) Available for Service Tab - Add a New Service Line")]
        [global::NUnit.Framework.CategoryAttribute("Feature:GTR-UAT-RTS-027MoveRequestTab-ViewMoveRequests")]
        [global::NUnit.Framework.TestCaseAttribute("Panel Operations Manager", "0", null)]
        public async global::System.Threading.Tasks.Task _01AvailableForServiceTab_AddANewServiceLine(string role, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Feature:GTR-UAT-RTS-027MoveRequestTab-ViewMoveRequests"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("role", role);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("01) Available for Service Tab - Add a New Service Line", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync(string.Format("I sign as {0}", role), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
 await testRunner.AndAsync("I open application Depot Management (BRDF)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table839 = new global::Reqnroll.Table(new string[] {
                            "Yard Asset"});
                table839.AddRow(new string[] {
                            "PETERBOROUGH-NENE-YARD"});
#line 9
 await testRunner.AndAsync("I filter table Yard Asset:", ((string)(null)), table839, "And ");
#line hidden
#line 12
 await testRunner.AndAsync("I select no.1 record Service Management table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
 await testRunner.AndAsync("I go to Available for Service Tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
 await testRunner.AndAsync("I go to Departures sub tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
 await testRunner.AndAsync("I select Add a New Service Line", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
 await testRunner.AndAsync("I select value lookup of Destination", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table840 = new global::Reqnroll.Table(new string[] {
                            "Destination"});
                table840.AddRow(new string[] {
                            "PETERBOROUGH-NENE-YARD"});
#line 17
 await testRunner.AndAsync("I filter table Destination:", ((string)(null)), table840, "And ");
#line hidden
#line 20
 await testRunner.AndAsync("I select no.1 record Destination table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
 await testRunner.AndAsync("I select value lookup of Direction field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table841 = new global::Reqnroll.Table(new string[] {
                            "Direction"});
                table841.AddRow(new string[] {
                            "S"});
#line 22
 await testRunner.AndAsync("I filter Direction:", ((string)(null)), table841, "And ");
#line hidden
#line 25
 await testRunner.AndAsync("I select no.1 record Direction table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table842 = new global::Reqnroll.Table(new string[] {
                            "Departure Time",
                            "Arrival Time"});
                table842.AddRow(new string[] {
                            "02:00:00",
                            "02:25:00"});
#line 26
 await testRunner.AndAsync("I enter Departure and Arrival Time:", ((string)(null)), table842, "And ");
#line hidden
                global::Reqnroll.Table table843 = new global::Reqnroll.Table(new string[] {
                            "Run Number",
                            "Memo",
                            "Duty Number"});
                table843.AddRow(new string[] {
                            "SU311",
                            "Test",
                            "1234"});
#line 29
 await testRunner.AndAsync("I enter Service Line Details:", ((string)(null)), table843, "And ");
#line hidden
#line 32
 await testRunner.AndAsync("I select OK dialog button of Add a New Service Line", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
 await testRunner.AndAsync("I take screenshot of New Service Line", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
 await testRunner.AndAsync("I go to Available for Service sub tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
 await testRunner.AndAsync("I select action Allocate Departure Timetable", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
 await testRunner.AndAsync("I select no.1 record of Allocate Departure Timetable table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
 await testRunner.AndAsync("I select Allocate Departure Service", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
 await testRunner.AndAsync("I take screenshot of Allocate Departure Service", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
 await testRunner.AndAsync("I go to Departures sub tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
 await testRunner.AndAsync("I select action Depart Train", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
 await testRunner.AndAsync("I select value lookup of Delay Code", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table844 = new global::Reqnroll.Table(new string[] {
                            "Delay Code"});
                table844.AddRow(new string[] {
                            "ES"});
#line 42
 await testRunner.AndAsync("I filter Delay Code:", ((string)(null)), table844, "And ");
#line hidden
#line 45
 await testRunner.AndAsync("I select no.1 record from Delay Code table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table845 = new global::Reqnroll.Table(new string[] {
                            "Delay Reason"});
                table845.AddRow(new string[] {
                            "TESTING"});
#line 46
 await testRunner.AndAsync("I enter Delay Reason:", ((string)(null)), table845, "And ");
#line hidden
#line 49
 await testRunner.AndAsync("I click OK dialog button of Depart Train", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
 await testRunner.AndAsync("I take screenshot of departed train", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
 await testRunner.AndAsync("I go to Recently Departed sub Tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
 await testRunner.AndAsync("I take screenshot of Recently Departed sub Tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("02) In Service / Arriving Tab - Arriving a Train that is in Service")]
        [global::NUnit.Framework.TestCaseAttribute("Panel Operations Manager", "1", null)]
        public async global::System.Threading.Tasks.Task _02InServiceArrivingTab_ArrivingATrainThatIsInService(string role, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("role", role);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("02) In Service / Arriving Tab - Arriving a Train that is in Service", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 60
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 61
 await testRunner.GivenAsync(string.Format("I sign as {0}", role), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 62
 await testRunner.AndAsync("I open application Depot Management (BRDF)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table846 = new global::Reqnroll.Table(new string[] {
                            "Yard Asset"});
                table846.AddRow(new string[] {
                            "PETERBOROUGH-NENE-YARD"});
#line 63
 await testRunner.AndAsync("I filter table Yard Asset:", ((string)(null)), table846, "And ");
#line hidden
#line 66
 await testRunner.AndAsync("I select no.1 record Yard Asset table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 67
 await testRunner.AndAsync("I go to In Service / Arriving Tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 68
 await testRunner.AndAsync("I select action Arrive to Road", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 69
 await testRunner.AndAsync("I select value lookup of Arrival Road field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table847 = new global::Reqnroll.Table(new string[] {
                            "Arrival Road"});
                table847.AddRow(new string[] {
                            "PN-05-RD"});
#line 70
 await testRunner.AndAsync("I filter Arrival Road:", ((string)(null)), table847, "And ");
#line hidden
#line 73
 await testRunner.AndAsync("I select no.1 record from Arrival Road table", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
 await testRunner.AndAsync("I set Arrived", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
 await testRunner.AndAsync("I set Accepted", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
 await testRunner.AndAsync("I set Yard", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
 await testRunner.AndAsync("I select dialog Arrive Service button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
 await testRunner.AndAsync("I take screenshot of Arrive Service Test", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
 await testRunner.AndAsync("I go to Depot View Tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
 await testRunner.AndAsync("I take screenshot of Depot View Tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("03) Create a Move Request")]
        [global::NUnit.Framework.TestCaseAttribute("Panel Operations Manager", "2", null)]
        public async global::System.Threading.Tasks.Task _03CreateAMoveRequest(string role, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("role", role);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("03) Create a Move Request", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 89
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 90
 await testRunner.GivenAsync(string.Format("I sign as {0}", role), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 91
 await testRunner.AndAsync("I open application Depot Management (BRDF)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table848 = new global::Reqnroll.Table(new string[] {
                            "Yard Asset"});
                table848.AddRow(new string[] {
                            "PETERBOROUGH-NENE-YARD"});
#line 92
 await testRunner.AndAsync("I filter table Yard Asset:", ((string)(null)), table848, "And ");
#line hidden
#line 95
 await testRunner.AndAsync("I select no.1 record Yard Asset table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 96
 await testRunner.AndAsync("I select Unit on Roads", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 97
 await testRunner.AndAsync("I Select Create Move Request", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 98
 await testRunner.AndAsync("I select value lookup of Road field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table849 = new global::Reqnroll.Table(new string[] {
                            "Road"});
                table849.AddRow(new string[] {
                            "PN-06-RD"});
#line 99
 await testRunner.AndAsync("I filter Road:", ((string)(null)), table849, "And ");
#line hidden
#line 102
 await testRunner.AndAsync("I select no.1 record from Road table", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 103
 await testRunner.AndAsync("I set Move By Date", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 104
 await testRunner.AndAsync("I click ok dailog button of Create Move Request", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 105
 await testRunner.AndAsync("I take screenshot of Create Move Request", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 106
 await testRunner.AndAsync("I go to At Location Tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 107
 await testRunner.AndAsync("I click action Create Move Request", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 109
 await testRunner.AndAsync("I select value lookup of Road field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table850 = new global::Reqnroll.Table(new string[] {
                            "Road"});
                table850.AddRow(new string[] {
                            "PN-04-RD"});
#line 110
 await testRunner.AndAsync("I filter Road:", ((string)(null)), table850, "And ");
#line hidden
#line 113
 await testRunner.AndAsync("I select no.1 record from Road table", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 114
 await testRunner.AndAsync("I modify Move By Date", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 115
 await testRunner.AndAsync("I click ok dailog button of Move Request Details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 116
 await testRunner.AndAsync("I take screenshot of Move Request Details Test Scenario", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("04) Move Request Tab - View Move Requests")]
        [global::NUnit.Framework.TestCaseAttribute("Panel Operations Manager", "3", null)]
        public async global::System.Threading.Tasks.Task _04MoveRequestTab_ViewMoveRequests(string role, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("role", role);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("04) Move Request Tab - View Move Requests", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 126
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 127
 await testRunner.GivenAsync(string.Format("I sign as {0}", role), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 128
 await testRunner.AndAsync("I open application Depot Management (BRDF)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table851 = new global::Reqnroll.Table(new string[] {
                            "Yard Asset"});
                table851.AddRow(new string[] {
                            "PETERBOROUGH-NENE-YARD"});
#line 129
 await testRunner.AndAsync("I filter table Yard Asset:", ((string)(null)), table851, "And ");
#line hidden
#line 132
 await testRunner.AndAsync("I select no.1 record Yard Asset table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 133
 await testRunner.AndAsync("I go to Move Request Tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 134
 await testRunner.AndAsync("I verify Status", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 135
 await testRunner.AndAsync("I verify Location", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 136
 await testRunner.AndAsync("I verify Move To", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 137
 await testRunner.AndAsync("I verify Requested", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 138
 await testRunner.AndAsync("I verify Move By Date", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 140
 await testRunner.AndAsync("I take screenshot of Move Request Details Tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
