// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace GTR_AUTOMATED.Features.Administration.CMSScripts
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("0.0.04 - Creating new Training Course Job Plans")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class _0_0_04_CreatingNewTrainingCourseJobPlansFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Administration/CMS Scripts", "0.0.04 - Creating new Training Course Job Plans", @"There is a need to create a new training course job plan(s) (to be applied to a Training Course Work Order for MC Courses and Annual Assessments). There are two steps to this process:

Creating the Job Plan for the Parent Work Order for Assignment of Trainees;
Creating the Job Plan for Children Work Orders to list Tasks for Qualifications.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "GTR-UAT-CMS-004.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Administration/CMS Scripts/GTR-UAT-CMS-004.feature.ndjson", 7);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("01) Creation of a Qualification")]
        [global::NUnit.Framework.CategoryAttribute("Feature:0.0.04-CreatingnewTrainingCourseJobPlans")]
        [global::NUnit.Framework.TestCaseAttribute("training manager", "0", null)]
        public async global::System.Threading.Tasks.Task _01CreationOfAQualification(string role, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Feature:0.0.04-CreatingnewTrainingCourseJobPlans"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("role", role);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("01) Creation of a Qualification", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 9
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
   await testRunner.GivenAsync("I sign as training manager", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 11
   await testRunner.AndAsync("I open application Qualifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
   await testRunner.AndAsync("I select New Qualification", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "Qualification Code",
                            "Qualification Description"});
                table17.AddRow(new string[] {
                            "QUF 5",
                            "Qualification for Unit Familiarity"});
#line 13
   await testRunner.AndAsync("I enter Qualifications Details:", ((string)(null)), table17, "And ");
#line hidden
#line 16
   await testRunner.AndAsync("I open Select Value lookup of Qualification Type field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "Qualification Type"});
                table18.AddRow(new string[] {
                            "REFRESH"});
#line 17
   await testRunner.AndAsync("I select Qualification Type:", ((string)(null)), table18, "And ");
#line hidden
#line 20
      await testRunner.AndAsync("I select Qualification Type", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "Power Up Parent Qualification",
                            "Duration"});
                table19.AddRow(new string[] {
                            "TQ0099",
                            "2"});
#line 21
   await testRunner.AndAsync("I enter following:", ((string)(null)), table19, "And ");
#line hidden
#line 24
   await testRunner.AndAsync("I open Select Value lookup of Duration Period field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
      await testRunner.AndAsync("I select Years from the list", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "Required Use Length"});
                table20.AddRow(new string[] {
                            "6"});
#line 26
   await testRunner.AndAsync("I enter Required Use Length:", ((string)(null)), table20, "And ");
#line hidden
#line 29
   await testRunner.AndAsync("I open Select Value lookup of Required Use Period field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
      await testRunner.AndAsync("I select MONTHS from the list", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
   await testRunner.AndAsync("I select New Row under the Required Craft and Skill Level section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
   await testRunner.AndAsync("I choose Select Value from Detail Menu of Craft field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "Craft",
                            "Skill-Level"});
                table21.AddRow(new string[] {
                            "TRAINING",
                            "SEMI-SKILLED"});
#line 33
   await testRunner.AndAsync("I filter table Craft and Skill Level:", ((string)(null)), table21, "And ");
#line hidden
#line 36
      await testRunner.AndAsync("I select no. 1 record from Craft and Skill Level table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
   await testRunner.AndAsync("I save record", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
   await testRunner.AndAsync("I take screenshot of Craft Skill-Level", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
   await testRunner.AndAsync("I delete Craft Skill-Level", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
   await testRunner.AndAsync("I save record", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
   await testRunner.AndAsync("I change qualifications change status inactive", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
   await testRunner.AndAsync("I select Ok Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
   await testRunner.AndAsync("I verify status is INACTIVE", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
      await testRunner.AndAsync("I take screenshot of Creating new Training Course Job Plans Test Scenario one", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("02) Creating new Training Course Job Plans")]
        [global::NUnit.Framework.TestCaseAttribute("cms admin team leader", "1", null)]
        public async global::System.Threading.Tasks.Task _02CreatingNewTrainingCourseJobPlans(string role, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("role", role);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("02) Creating new Training Course Job Plans", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 53
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 54
  await testRunner.GivenAsync("I sign as cms admin team leader", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 55
  await testRunner.AndAsync("I open application Job Plans (Tr)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
  await testRunner.AndAsync("I select New Job Plan", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "ID",
                            "Description"});
                table22.AddRow(new string[] {
                            "CMS-210",
                            "New Starter Assessment - Tasks"});
#line 57
  await testRunner.AndAsync("I enter Job Plan:", ((string)(null)), table22, "And ");
#line hidden
#line 60
  await testRunner.AndAsync("I open Select Value lookup of Organisation field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
  await testRunner.AndAsync("I select no. 1 record from Organisation table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
  await testRunner.AndAsync("I open Select Value lookup of Site field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
  await testRunner.AndAsync("I select no. 1 record from Site table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
  await testRunner.AndAsync("I select details section maximize option", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "Duration"});
                table23.AddRow(new string[] {
                            "4:00"});
#line 65
  await testRunner.AndAsync("I enter Duration:", ((string)(null)), table23, "And ");
#line hidden
#line 68
  await testRunner.AndAsync("I select New Row button under Job Plans Tasks section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "Task Description"});
                table24.AddRow(new string[] {
                            "Unit familiarity"});
#line 69
  await testRunner.AndAsync("I enter Task Description:", ((string)(null)), table24, "And ");
#line hidden
#line 72
  await testRunner.AndAsync("I open Select Value lookup of Qualifications field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
  await testRunner.AndAsync("I select yes dialog button of System Message", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
  await testRunner.AndAsync("I select New Row", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
  await testRunner.AndAsync("I open Select Value lookup of Qualification Requirements field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "Qualification"});
                table25.AddRow(new string[] {
                            "QUF 5"});
#line 76
  await testRunner.AndAsync("I filter Qualification Requirements:", ((string)(null)), table25, "And ");
#line hidden
#line 79
  await testRunner.AndAsync("I select no. 1 record from Qualification Requirements table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
  await testRunner.AndAsync("I Press Ok dialog button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 81
  await testRunner.AndAsync("I save record", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 82
  await testRunner.AndAsync("I set Qualification status ACTIVE", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
  await testRunner.AndAsync("I click Ok", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 84
  await testRunner.AndAsync("I verify Job Plans status ACTIVE", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
  await testRunner.AndAsync("I take screenshot of Creating new Training Course Job Plans Test Scenario two", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("03) Create Job Plan to Assign Trainee")]
        [global::NUnit.Framework.TestCaseAttribute("cms admin team leader", "2", null)]
        public async global::System.Threading.Tasks.Task _03CreateJobPlanToAssignTrainee(string role, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("role", role);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("03) Create Job Plan to Assign Trainee", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 93
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 94
  await testRunner.GivenAsync("I sign as cms admin team leader", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 95
  await testRunner.AndAsync("I open application Job Plans (Tr)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 96
  await testRunner.AndAsync("I select New Job Plan", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                            "ID",
                            "Description"});
                table26.AddRow(new string[] {
                            "CMS-202",
                            "New Starter Assessment"});
#line 97
  await testRunner.AndAsync("I enter Job Plan:", ((string)(null)), table26, "And ");
#line hidden
#line 100
  await testRunner.AndAsync("I open Select Value lookup of Organisation field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 101
  await testRunner.AndAsync("I select no. 1 record from Organisation table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 102
  await testRunner.AndAsync("I open Select Value lookup of Site field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 103
  await testRunner.AndAsync("I select no. 1 record from Site table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 104
  await testRunner.AndAsync("I select details section maximize option", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table27 = new global::Reqnroll.Table(new string[] {
                            "Duration"});
                table27.AddRow(new string[] {
                            "4:00"});
#line 105
  await testRunner.AndAsync("I enter Duration:", ((string)(null)), table27, "And ");
#line hidden
#line 108
  await testRunner.AndAsync("I select New Row button under Job Plans Tasks section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table28 = new global::Reqnroll.Table(new string[] {
                            "Task Description"});
                table28.AddRow(new string[] {
                            "Unit familiarity"});
#line 109
  await testRunner.AndAsync("I enter Task Description:", ((string)(null)), table28, "And ");
#line hidden
#line 112
  await testRunner.AndAsync("I open Select Value lookup of Nested Job Plan field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table29 = new global::Reqnroll.Table(new string[] {
                            "Description"});
                table29.AddRow(new string[] {
                            "New Starter Assessment - Tasks"});
#line 113
   await testRunner.AndAsync("I filter Nested Job Plan:", ((string)(null)), table29, "And ");
#line hidden
#line 116
  await testRunner.AndAsync("I select no. 1 record from Nested Job Plan table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 117
     await testRunner.AndAsync("I save record", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 118
  await testRunner.AndAsync("I select New Row button under Job Plans Tasks section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table30 = new global::Reqnroll.Table(new string[] {
                            "Task Description"});
                table30.AddRow(new string[] {
                            "Unit familiarity 2"});
#line 119
  await testRunner.AndAsync("I enter Task Description:", ((string)(null)), table30, "And ");
#line hidden
#line 122
  await testRunner.AndAsync("I open Select Value lookup of Nested Job Plan field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table31 = new global::Reqnroll.Table(new string[] {
                            "Description"});
                table31.AddRow(new string[] {
                            "New Starter Assessment - Tasks"});
#line 123
  await testRunner.AndAsync("I filter Nested Job Plan:", ((string)(null)), table31, "And ");
#line hidden
#line 126
  await testRunner.AndAsync("I select no. 1 record from Nested Job Plan table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 127
  await testRunner.AndAsync("I select New Row button under Job Plans Tasks section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table32 = new global::Reqnroll.Table(new string[] {
                            "Task Description"});
                table32.AddRow(new string[] {
                            "Unit familiarity 3"});
#line 128
  await testRunner.AndAsync("I enter Task Description:", ((string)(null)), table32, "And ");
#line hidden
#line 131
  await testRunner.AndAsync("I open Select Value lookup of Nested Job Plan field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table33 = new global::Reqnroll.Table(new string[] {
                            "Description"});
                table33.AddRow(new string[] {
                            "New Starter Assessment - Tasks"});
#line 132
  await testRunner.AndAsync("I filter Nested Job Plan:", ((string)(null)), table33, "And ");
#line hidden
#line 135
  await testRunner.AndAsync("I select no. 1 record from Nested Job Plan table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 136
  await testRunner.AndAsync("I save record", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 137
  await testRunner.AndAsync("I select New Row button under Planned Labor section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table34 = new global::Reqnroll.Table(new string[] {
                            "Task Value"});
                table34.AddRow(new string[] {
                            "10"});
#line 138
  await testRunner.AndAsync("I enter Task Value:", ((string)(null)), table34, "And ");
#line hidden
#line 141
     await testRunner.AndAsync("I choose Select Value from Detail Menu of Craft", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table35 = new global::Reqnroll.Table(new string[] {
                            "Craft",
                            "Skill-Level"});
                table35.AddRow(new string[] {
                            "TRAINING",
                            "SKILLED"});
#line 142
  await testRunner.AndAsync("I filter table Craft:", ((string)(null)), table35, "And ");
#line hidden
#line 145
     await testRunner.AndAsync("I select no. 2 record from Craft table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 146
  await testRunner.AndAsync("I select New Row button under Planned Labor section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table36 = new global::Reqnroll.Table(new string[] {
                            "Task Value"});
                table36.AddRow(new string[] {
                            "20"});
#line 147
  await testRunner.AndAsync("I enter Task Value:", ((string)(null)), table36, "And ");
#line hidden
#line 150
     await testRunner.AndAsync("I choose Select Value from Detail Menu of Craft", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table37 = new global::Reqnroll.Table(new string[] {
                            "Craft",
                            "Skill-Level"});
                table37.AddRow(new string[] {
                            "TRAINING",
                            "SKILLED"});
#line 151
  await testRunner.AndAsync("I filter table Craft:", ((string)(null)), table37, "And ");
#line hidden
#line 154
     await testRunner.AndAsync("I select no. 2 record from Craft table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 155
  await testRunner.AndAsync("I select New Row button under Planned Labor section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table38 = new global::Reqnroll.Table(new string[] {
                            "Task Value"});
                table38.AddRow(new string[] {
                            "30"});
#line 156
  await testRunner.AndAsync("I enter Task Value:", ((string)(null)), table38, "And ");
#line hidden
#line 159
     await testRunner.AndAsync("I choose Select Value from Detail Menu of Craft", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table39 = new global::Reqnroll.Table(new string[] {
                            "Craft",
                            "Skill-Level"});
                table39.AddRow(new string[] {
                            "TRAINING",
                            "SKILLED"});
#line 160
  await testRunner.AndAsync("I filter table Craft:", ((string)(null)), table39, "And ");
#line hidden
#line 163
     await testRunner.AndAsync("I select no. 2 record from Craft table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 164
     await testRunner.AndAsync("I save record", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 165
  await testRunner.AndAsync("I set Job Plan status ACTIVE", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 166
  await testRunner.AndAsync("I click Ok", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 167
  await testRunner.AndAsync("I verify status ACTIVE", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 168
  await testRunner.AndAsync("I take screenshot of Creating new Training Course Job Plans Test Scenario three", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("04) Delete Training Course Job Plans")]
        [global::NUnit.Framework.TestCaseAttribute("training manager", "3", null)]
        public async global::System.Threading.Tasks.Task _04DeleteTrainingCourseJobPlans(string role, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("role", role);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("04) Delete Training Course Job Plans", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 176
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 177
      await testRunner.GivenAsync("I sign as training manager", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 178
   await testRunner.AndAsync("I open application Job Plans (Tr)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table40 = new global::Reqnroll.Table(new string[] {
                            "Job Plans"});
                table40.AddRow(new string[] {
                            "CMS-210"});
#line 179
   await testRunner.AndAsync("I filter table Job Plans:", ((string)(null)), table40, "And ");
#line hidden
#line 182
      await testRunner.AndAsync("I select no. 1 record from Job Plans table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 183
   await testRunner.AndAsync("I select delete Job Plans", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 184
   await testRunner.AndAsync("I press Yes button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 185
   await testRunner.AndAsync("I verify Job Plans table has no records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 186
   await testRunner.AndAsync("I take screenshot of Creating new Training Course Job Plans Test Scenario four", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("05) Delete Job Plan")]
        [global::NUnit.Framework.TestCaseAttribute("training manager", "4", null)]
        public async global::System.Threading.Tasks.Task _05DeleteJobPlan(string role, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("role", role);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("05) Delete Job Plan", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 194
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 195
     await testRunner.GivenAsync("I sign as training manager", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 196
  await testRunner.AndAsync("I open application Job Plans (Tr)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table41 = new global::Reqnroll.Table(new string[] {
                            "Job Plans"});
                table41.AddRow(new string[] {
                            "CMS-202"});
#line 197
  await testRunner.AndAsync("I filter table Job Plans:", ((string)(null)), table41, "And ");
#line hidden
#line 200
     await testRunner.AndAsync("I select no. 1 record from Job Plans table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 201
  await testRunner.AndAsync("I select delect Job Plan", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 202
  await testRunner.AndAsync("I select Yes button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 203
  await testRunner.AndAsync("I verify Job Plans table has no records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 204
  await testRunner.AndAsync("I take screenshot of Creating new Training Course Job Plans Test Scenario five", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
