// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace GTR_AUTOMATED.Features.Administration.CMSScripts
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("0.0.08a - Allocating a Trainer, Classroom & Trainees to a Training Course (in Gra" +
        "phical Assignment)")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class _0_0_08A_AllocatingATrainerClassroomTraineesToATrainingCourseInGraphicalAssignmentFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Administration/CMS Scripts", "0.0.08a - Allocating a Trainer, Classroom & Trainees to a Training Course (in Gra" +
                "phical Assignment)", "To allocate a trainer, classroom and trainees to a scheduled training course usin" +
                "g the Graphical Assignment application.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "GTR-UAT-CMS-008a.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Administration/CMS Scripts/GTR-UAT-CMS-008a.feature.ndjson", 4);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("01) Allocating a Trainer, Classroom & Trainees to a Training Course (in Graphical" +
            " Assignment)")]
        [global::NUnit.Framework.CategoryAttribute("Feature:0.0.08a-AllocatingaTrainer,Classroom&TraineestoaTrainingCourse(inGraphica" +
            "lAssignment)")]
        [global::NUnit.Framework.TestCaseAttribute("training manager", "0", null)]
        public async global::System.Threading.Tasks.Task _01AllocatingATrainerClassroomTraineesToATrainingCourseInGraphicalAssignment(string role, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Feature:0.0.08a-AllocatingaTrainer,Classroom&TraineestoaTrainingCourse(inGraphica" +
                        "lAssignment)"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("role", role);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("01) Allocating a Trainer, Classroom & Trainees to a Training Course (in Graphical" +
                    " Assignment)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await testRunner.GivenAsync("I sign as training manager", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
 await testRunner.AndAsync("I open application Graphical Assignment", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
 await testRunner.AndAsync("I select create new schedule", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table75 = new global::Reqnroll.Table(new string[] {
                            "ID",
                            "Description"});
                table75.AddRow(new string[] {
                            "TAUTO-CMS",
                            "Allocating a Trainee to a Training Course Test"});
#line 11
 await testRunner.AndAsync("I enter Assignment:", ((string)(null)), table75, "And ");
#line hidden
#line 14
 await testRunner.AndAsync("I choose Select Value from Detail Menu of calendar field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
 await testRunner.AndAsync("I select GTRBASE", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
 await testRunner.AndAsync("I open Select Value lookup of Shift field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
 await testRunner.AndAsync("I select no. 1 from Shift table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
 await testRunner.AndAsync("I Press Ok dialog select Shift button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
 await testRunner.AndAsync("I select Copy Query button under Work Queries section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table76 = new global::Reqnroll.Table(new string[] {
                            "Query"});
                table76.AddRow(new string[] {
                            "MXR_CMS_SCHEDULED_ADMIN"});
#line 20
 await testRunner.AndAsync("I filter table Query:", ((string)(null)), table76, "And ");
#line hidden
#line 23
 await testRunner.AndAsync("I select no. 1 from Query table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
 await testRunner.AndAsync("I press dialog ok button of copy Query", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
 await testRunner.AndAsync("I save record", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
 await testRunner.AndAsync("I wait for Query to load", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
 await testRunner.AndAsync("I select list view button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table77 = new global::Reqnroll.Table(new string[] {
                            "Description"});
                table77.AddRow(new string[] {
                            "Allocating a Trainee to a Training Course Test"});
#line 28
 await testRunner.AndAsync("I filter Graphical Scheduling:", ((string)(null)), table77, "And ");
#line hidden
#line 31
 await testRunner.AndAsync("I select no. 1 record from Graphical table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
 await testRunner.AndAsync("I go to tab Work View", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
 await testRunner.AndAsync("I wait for Work View page to load", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
 await testRunner.AndAsync("I take screenshot of Allocating a Trainer, Classroom & Trainees to a Training Cou" +
                        "rse (in Graphical Assignment) Test Scenario one", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("02) Delete Allocating a Trainer & Classroom to a Training Course (in Graphical As" +
            "signment)")]
        [global::NUnit.Framework.TestCaseAttribute("training manager", "1", null)]
        public async global::System.Threading.Tasks.Task _02DeleteAllocatingATrainerClassroomToATrainingCourseInGraphicalAssignment(string role, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("role", role);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("02) Delete Allocating a Trainer & Classroom to a Training Course (in Graphical As" +
                    "signment)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 46
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 47
      await testRunner.GivenAsync("I sign as training manager", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 48
   await testRunner.AndAsync("I open application Graphical Assignment", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table78 = new global::Reqnroll.Table(new string[] {
                            "ID"});
                table78.AddRow(new string[] {
                            "TAUTO-CMS"});
#line 49
   await testRunner.AndAsync("I filter table Graphical Scheduling:", ((string)(null)), table78, "And ");
#line hidden
#line 52
      await testRunner.AndAsync("I select no. 1 record from Graphical Scheduling table records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
   await testRunner.AndAsync("I select delete Graphical Scheduling record", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
   await testRunner.AndAsync("I select Yes button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
   await testRunner.AndAsync("I verify Graphical Scheduling table has no records", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
   await testRunner.AndAsync("I take screenshot of Allocating a Trainer, Classroom & Trainees to a Training Cou" +
                        "rse (in Graphical Assignment) Test Scenario two", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
